# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Presenter
version:      1.01
version_from: lib/Data/Presenter.pm
installdirs:  site
requires:
    IO::Capture:                   0.05
    IO::Capture::Extended:         0.09
    List::Compare:                 0.15
    Tie::File:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
