--- #YAML:1.0
name:                Data-Presenter
version:             1.03
abstract:            Reformat database reports
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::Capture:                   0.05
    IO::Capture::Extended:         0.09
    List::Compare:                 0.15
    Tie::File:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
